// the hello world program [// the hello world program] 
console.log('Hello World'); [console.log('Hello World')]
console.log('Hello World'); [console.log('Hello World')]
console.log('Hello World'); [console.log('Hello World')]
console.log('Hello World'); [console.log('Hello World')]
console.log('Hello World'); [console.log('Hello World')]
console.log('Hello World'); [console.log('Hello World')]
console.log('Hello World'); [console.log('Hello World')]